// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oviycfskyptjnseiztux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92aXljZnNreXB0am5zZWl6dHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNTE1MTIsImV4cCI6MjA4ODcyNzUxMn0.sDWhSmTSxCtodiNO_DSUhYId4LWcUmAt7BEDreSNOJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});